; <?php die("Access denied"); ?>
[general]
title = "iCauseFX"
password = "$2y$10$97IH4rsp6fb.p5KIFfjVH.xZuFtghq5h.cKV4VuKQPhZCQdmJzeMS"
useicons = "true"
usemargins = "true"
bg = "#f2f2f2"
tabborder = "#cecece"
tabhighlight = "#f44343"
tabcoloractive = "#ffffff"
fontcoloractive = "#f44343"
tabshadowactive = "#808080"
tabcolor = "#ffffff"
fontcolor = "#000000"
tabshadow = "#c7c6c6"
[Sonarr]
url = "https://sonarr.tv/"
icon = "fa-desktop"
enabled = "true"
group = "1"
[QNAP]
url = "https://www.qnap.com/i/useng/"
icon = "fa-cubes"
enabled = "true"
group = "1"
[Movies]
url = "https://couchpota.to/"
icon = "fa-film"
enabled = "true"
default = "true"
group = "1"
[Proxy]
url = "https://www.glype.com/"
icon = "fa-bug"
enabled = "true"
guest = "true"
group = "1"
[Request]
url = "https://plexrequests.8bits.ca/"
icon = "fa-search"
enabled = "true"
guest = "true"
group = "1"
[Server]
url = "https://phpsysinfo.github.io/phpsysinfo/"
icon = "fa-database"
enabled = "true"
group = "1"
[NZB]
url = "https://nzbget.net/"
icon = "fa-cloud-download"
enabled = "true"
group = "1"
[groups]
groups = "1"